# Generated by Django 5.2.1 on 2025-06-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='hobby',
            field=models.CharField(default='게임', max_length=50),
        ),
    ]
