# Generated by Django 5.2.1 on 2025-07-07 03:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signupFT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(choices=[('exchange-review', '교환후기'), ('offline-sharing', '나눔'), ('offline-proxy', '대리구매'), ('offline-status', '현황 공유'), ('offline-companion', '동행'), ('recent-activity', '최근 활동')], max_length=30)),
                ('icon', models.CharField(default='⭐', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='특징 리스트를 줄바꿈으로 구분')),
                ('stat_total', models.CharField(max_length=50)),
                ('stat_label_total', models.CharField(max_length=50)),
                ('stat_secondary', models.CharField(blank=True, max_length=50, null=True)),
                ('stat_label_secondary', models.CharField(blank=True, max_length=50, null=True)),
                ('stat_tertiary', models.CharField(blank=True, max_length=50, null=True)),
                ('stat_label_tertiary', models.CharField(blank=True, max_length=50, null=True)),
                ('write_url', models.URLField(blank=True, null=True)),
                ('view_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='태그명')),
            ],
        ),
        migrations.CreateModel(
            name='ProxyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='태그명')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='태그명')),
            ],
        ),
        migrations.CreateModel(
            name='SharingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='태그명')),
            ],
        ),
        migrations.CreateModel(
            name='CompanionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문')),
                ('category', models.CharField(choices=[('콘서트', '콘서트'), ('팬사인회', '팬사인회'), ('팝업스토어', '팝업스토어'), ('전시회', '전시회'), ('굿즈샵', '굿즈샵'), ('기타', '기타')], max_length=20, verbose_name='카테고리')),
                ('artist', models.CharField(max_length=50, verbose_name='아티스트')),
                ('event_date', models.DateTimeField(verbose_name='행사 날짜 및 시간')),
                ('location', models.CharField(max_length=100, verbose_name='위치')),
                ('max_people', models.PositiveIntegerField(verbose_name='최대 모집 인원')),
                ('status', models.CharField(choices=[('모집중', '모집중'), ('모집완료', '모집완료'), ('진행중', '진행중')], default='모집중', max_length=10, verbose_name='모집 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='댓글 수')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_posts', to='signupFT.user', verbose_name='작성자')),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_companions', to='signupFT.user', verbose_name='참여자 목록')),
            ],
        ),
        migrations.CreateModel(
            name='CompanionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='companion_images/', verbose_name='첨부 이미지')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='이미지 설명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.companionpost')),
            ],
        ),
        migrations.CreateModel(
            name='CompanionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.companionpost', verbose_name='게시글')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='후기 내용')),
                ('artist', models.CharField(default='기타', max_length=50, verbose_name='아티스트')),
                ('method', models.CharField(choices=[('온라인', '온라인'), ('오프라인', '오프라인')], max_length=20, verbose_name='교환 방식')),
                ('transaction_type', models.CharField(choices=[('교환', '교환'), ('양도', '양도')], default='교환', max_length=10, verbose_name='거래 방식')),
                ('overall_score', models.PositiveSmallIntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], verbose_name='총 평점 (1~5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='signupFT.user', verbose_name='교환 상대방')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to='signupFT.user', verbose_name='작성자')),
                ('tags', models.ManyToManyField(blank=True, related_name='reviews', to='community.reviewtag', verbose_name='태그')),
            ],
        ),
        migrations.CreateModel(
            name='ProxyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('artist', models.CharField(max_length=50, verbose_name='아티스트')),
                ('category', models.CharField(choices=[('앨범', '앨범'), ('포토카드', '포토카드'), ('굿즈', '굿즈'), ('콘서트', '콘서트')], max_length=20, verbose_name='카테고리')),
                ('status', models.CharField(choices=[('모집중', '모집중'), ('긴급모집', '긴급모집'), ('마감임박', '마감임박')], max_length=20, verbose_name='모집상태')),
                ('event_date', models.DateTimeField(verbose_name='이벤트 날짜 및 시간')),
                ('location', models.CharField(max_length=100, verbose_name='장소')),
                ('max_people', models.PositiveIntegerField(verbose_name='최대 모집 인원')),
                ('reward', models.CharField(max_length=100, verbose_name='수고비')),
                ('description', models.TextField(verbose_name='본문')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='댓글 수')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_posts', to='signupFT.user', verbose_name='작성자')),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_proxies', to='signupFT.user', verbose_name='참여자 목록')),
                ('tags', models.ManyToManyField(blank=True, related_name='proxy_posts', to='community.proxytag', verbose_name='태그')),
            ],
        ),
        migrations.CreateModel(
            name='ProxyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proxy_images/', verbose_name='첨부 이미지')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='이미지 설명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.proxypost')),
            ],
        ),
        migrations.CreateModel(
            name='ProxyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signupFT.user', verbose_name='작성자')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.proxypost', verbose_name='게시글')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review_images/', verbose_name='첨부 이미지')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='이미지 설명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.exchangereview')),
            ],
        ),
        migrations.CreateModel(
            name='SharingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('artist', models.CharField(default='기타', max_length=50, verbose_name='아티스트')),
                ('requirement', models.TextField(verbose_name='필수사항')),
                ('category', models.CharField(choices=[('앨범', '앨범'), ('굿즈', '굿즈'), ('기타', '기타')], max_length=20, verbose_name='카테고리')),
                ('type', models.CharField(choices=[('온라인', '온라인'), ('오프라인', '오프라인')], max_length=10, verbose_name='나눔 형태')),
                ('share_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='나눔 날짜')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='나눔 장소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_posts', to='signupFT.user', verbose_name='작성자')),
                ('tags', models.ManyToManyField(blank=True, related_name='sharing_posts', to='community.sharingtag', verbose_name='태그')),
            ],
        ),
        migrations.CreateModel(
            name='SharingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sharing_images/', verbose_name='첨부 이미지')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시각')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.sharingpost')),
            ],
        ),
    ]
