# Generated by Django 5.2.1 on 2025-07-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(choices=[('exchange-review', '교환후기'), ('offline-sharing', '나눔'), ('offline-proxy', '대리구매'), ('offline-status', '현황 공유'), ('offline-companion', '동행'), ('recent-activity', '최근 활동')], max_length=30)),
                ('icon', models.CharField(default='⭐', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='특징 리스트를 줄바꿈으로 구분')),
                ('stat_total', models.CharField(max_length=50)),
                ('stat_label_total', models.CharField(max_length=50)),
                ('stat_secondary', models.CharField(blank=True, max_length=50, null=True)),
                ('stat_label_secondary', models.CharField(blank=True, max_length=50, null=True)),
                ('stat_tertiary', models.CharField(blank=True, max_length=50, null=True)),
                ('stat_label_tertiary', models.CharField(blank=True, max_length=50, null=True)),
                ('write_url', models.URLField(blank=True, null=True)),
                ('view_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
