# Generated by Django 5.2.1 on 2025-07-07 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('signupFT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='태그명')),
            ],
        ),
        migrations.CreateModel(
            name='StatusPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('artist', models.CharField(max_length=50, verbose_name='아티스트')),
                ('category', models.CharField(choices=[('콘서트', '콘서트'), ('팝업스토어', '팝업스토어'), ('팬사인회', '팬사인회'), ('전시회', '전시회'), ('굿즈샵', '굿즈샵'), ('기타', '기타')], max_length=20, verbose_name='카테고리')),
                ('event_datetime', models.DateTimeField(verbose_name='이벤트 일시')),
                ('place', models.CharField(max_length=200, verbose_name='장소')),
                ('region', models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('부산', '부산'), ('대구', '대구'), ('인천', '인천'), ('광주', '광주'), ('대전', '대전'), ('울산', '울산'), ('강원', '강원'), ('충북', '충북'), ('충남', '충남'), ('전북', '전북'), ('전남', '전남'), ('경북', '경북'), ('경남', '경남'), ('제주', '제주'), ('기타', '기타')], max_length=20, verbose_name='지역')),
                ('content', models.TextField(verbose_name='본문 내용')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_posts', to='signupFT.user', verbose_name='작성자')),
                ('tags', models.ManyToManyField(blank=True, related_name='status_posts', to='community.statustag', verbose_name='태그')),
            ],
            options={
                'verbose_name': '현황 공유',
                'verbose_name_plural': '현황 공유',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='status_images/', verbose_name='첨부 이미지')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시각')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.statuspost')),
            ],
        ),
    ]
