# Generated by Django 5.2.1 on 2025-07-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_statustag_statuspost_statusimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionpost',
            name='report_level',
            field=models.CharField(choices=[('normal', '정상'), ('pending', '대기'), ('hidden', '숨김')], default='normal', max_length=10, verbose_name='신고 상태'),
        ),
        migrations.AddField(
            model_name='exchangereview',
            name='report_level',
            field=models.CharField(choices=[('normal', '정상'), ('pending', '대기'), ('hidden', '숨김')], default='normal', max_length=10, verbose_name='신고 상태'),
        ),
        migrations.AddField(
            model_name='proxypost',
            name='report_level',
            field=models.CharField(choices=[('normal', '정상'), ('pending', '대기'), ('hidden', '숨김')], default='normal', max_length=10, verbose_name='신고 상태'),
        ),
        migrations.AddField(
            model_name='sharingpost',
            name='report_level',
            field=models.CharField(choices=[('normal', '정상'), ('pending', '대기'), ('hidden', '숨김')], default='normal', max_length=10, verbose_name='신고 상태'),
        ),
        migrations.AddField(
            model_name='statuspost',
            name='report_level',
            field=models.CharField(choices=[('normal', '정상'), ('pending', '대기'), ('hidden', '숨김')], default='normal', max_length=10, verbose_name='신고 상태'),
        ),
    ]
