# Generated by Django 5.2.1 on 2025-07-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_companionpost_report_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companionimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='proxyimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='reviewimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='companionpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='exchangereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='proxycomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='proxypost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='sharingpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
