# Generated by Django 5.2.1 on 2025-07-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_companionimage_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingpost',
            name='type',
            field=models.CharField(choices=[('온라인', '온라인'), ('오프라인', '오프라인')], default='오프라인', max_length=10, verbose_name='나눔 형태'),
        ),
    ]
