# Generated by Django 5.2.1 on 2025-07-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_sharingpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspost',
            name='status',
            field=models.CharField(choices=[('진행중', '진행중'), ('마감', '마감')], default='진행중', max_length=10, verbose_name='게시글 상태'),
        ),
    ]
