# Generated by Django 5.2.1 on 2025-07-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_companionpost_tags_alter_proxypost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companionpost',
            name='event_date',
            field=models.DateTimeField(null=True, verbose_name='행사 날짜 및 시간'),
        ),
        migrations.AlterField(
            model_name='companionpost',
            name='max_people',
            field=models.PositiveIntegerField(null=True, verbose_name='최대 모집 인원'),
        ),
    ]
