# Generated by Django 5.2.1 on 2025-07-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_alter_companionpost_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionpost',
            name='report_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='신고 수'),
        ),
        migrations.AddField(
            model_name='exchangereview',
            name='report_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='신고 수'),
        ),
        migrations.AddField(
            model_name='proxypost',
            name='report_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='신고 수'),
        ),
        migrations.AddField(
            model_name='sharingpost',
            name='report_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='신고 수'),
        ),
        migrations.AddField(
            model_name='statuspost',
            name='report_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='신고 수'),
        ),
    ]
