# Generated by Django 5.2.1 on 2025-06-30 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='태그명')),
            ],
        ),
        migrations.CreateModel(
            name='ProxyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('artist', models.CharField(max_length=50, verbose_name='아티스트')),
                ('category', models.CharField(choices=[('앨범', '앨범'), ('포토카드', '포토카드'), ('굿즈', '굿즈'), ('콘서트', '콘서트')], max_length=20, verbose_name='카테고리')),
                ('status', models.CharField(choices=[('모집중', '모집중'), ('긴급모집', '긴급모집'), ('마감임박', '마감임박')], max_length=20, verbose_name='모집상태')),
                ('event_date', models.DateTimeField(verbose_name='이벤트 날짜 및 시간')),
                ('location', models.CharField(max_length=100, verbose_name='장소')),
                ('max_people', models.PositiveIntegerField(verbose_name='최대 모집 인원')),
                ('reward', models.CharField(max_length=100, verbose_name='수고비')),
                ('description', models.TextField(verbose_name='본문')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='댓글 수')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_proxies', to=settings.AUTH_USER_MODEL, verbose_name='참여자 목록')),
                ('tags', models.ManyToManyField(blank=True, related_name='proxy_posts', to='proxy.proxytag', verbose_name='태그')),
            ],
        ),
        migrations.CreateModel(
            name='ProxyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='proxy.proxypost', verbose_name='게시글')),
            ],
        ),
    ]
