# Generated by Django 5.2.1 on 2025-07-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
        migrations.CreateModel(
            name='ProxyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proxy_images/', verbose_name='첨부 이미지')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='이미지 설명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
            ],
        ),
        migrations.CreateModel(
            name='ProxyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('artist', models.CharField(max_length=50, verbose_name='아티스트')),
                ('category', models.CharField(choices=[('앨범', '앨범'), ('포토카드', '포토카드'), ('굿즈', '굿즈'), ('콘서트', '콘서트')], max_length=20, verbose_name='카테고리')),
                ('status', models.CharField(choices=[('모집중', '모집중'), ('긴급모집', '긴급모집'), ('마감임박', '마감임박')], max_length=20, verbose_name='모집상태')),
                ('event_date', models.DateTimeField(verbose_name='이벤트 날짜 및 시간')),
                ('location', models.CharField(max_length=100, verbose_name='장소')),
                ('max_people', models.PositiveIntegerField(verbose_name='최대 모집 인원')),
                ('reward', models.CharField(max_length=100, verbose_name='수고비')),
                ('description', models.TextField(verbose_name='본문')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='댓글 수')),
            ],
        ),
        migrations.CreateModel(
            name='ProxyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='태그명')),
            ],
        ),
    ]
