# Generated by Django 5.2.1 on 2025-07-04 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proxy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proxycomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='proxypost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='proxypost',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_proxies', to=settings.AUTH_USER_MODEL, verbose_name='참여자 목록'),
        ),
        migrations.AddField(
            model_name='proxyimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='proxy.proxypost'),
        ),
        migrations.AddField(
            model_name='proxycomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='proxy.proxypost', verbose_name='게시글'),
        ),
        migrations.AddField(
            model_name='proxypost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='proxy_posts', to='proxy.proxytag', verbose_name='태그'),
        ),
    ]
