# Generated by Django 5.2.1 on 2025-07-01 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문 내용')),
                ('category', models.CharField(choices=[('콘서트', '콘서트'), ('팝업스토어', '팝업스토어'), ('팬사인회', '팬사인회'), ('전시회', '전시회'), ('굿즈샵', '굿즈샵'), ('기타', '기타')], max_length=20, verbose_name='카테고리')),
                ('artist', models.CharField(max_length=50, verbose_name='아티스트')),
                ('region', models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('부산', '부산'), ('대구', '대구'), ('인천', '인천'), ('기타', '기타')], max_length=20, verbose_name='지역')),
                ('place', models.CharField(max_length=200, verbose_name='장소')),
                ('event_datetime', models.DateTimeField(verbose_name='이벤트 일시')),
                ('images', models.TextField(blank=True, help_text='쉼표로 구분된 이미지 URL 문자열', verbose_name='이미지 URL 목록')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '현황 공유',
                'verbose_name_plural': '현황 공유',
                'ordering': ['-created_at'],
            },
        ),
    ]
