# Generated by Django 5.2.1 on 2025-06-04 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_bfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='gstep',
            new_name='bstep',
        ),
    ]
