# Generated by Django 5.2.1 on 2025-07-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('notice_type', models.CharField(choices=[('일반', '일반'), ('업데이트', '업데이트'), ('점검', '점검')], default='일반', max_length=20, verbose_name='공지 유형')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='상단 고정')),
                ('file', models.FileField(blank=True, null=True, upload_to='notice_files/', verbose_name='첨부파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
