# Generated by Django 5.2.1 on 2025-07-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='id',
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
