# Generated by Django 5.2.1 on 2025-07-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpage', '0002_remove_notice_id_notice_notice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='notice_id',
        ),
        migrations.AddField(
            model_name='notice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
