# Generated by Django 5.2.1 on 2025-07-08 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpage', '0003_remove_notice_notice_id_notice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='file',
        ),
        migrations.CreateModel(
            name='NoticeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notice_files/', verbose_name='첨부 이미지')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adpage.notice')),
            ],
        ),
    ]
