# Generated by Django 5.2.1 on 2025-07-04 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='그룹 코드')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='그룹명')),
                ('name_en', models.CharField(default='', max_length=100, verbose_name='그룹영어명')),
                ('gender', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성'), ('U', '혼성/알 수 없음')], max_length=1, null=True, verbose_name='그룹 성별')),
                ('debut_date', models.DateField(blank=True, null=True, verbose_name='데뷔일')),
            ],
            options={
                'verbose_name': '아이돌 그룹',
                'verbose_name_plural': '아이돌 그룹 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='멤버 이름')),
                ('name_en', models.CharField(default='', max_length=100, verbose_name='멤버 영어이름')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='idols.group', verbose_name='소속 그룹')),
            ],
            options={
                'verbose_name': '아이돌 멤버',
                'verbose_name_plural': '아이돌 멤버 목록',
                'ordering': ['group__name', 'name'],
                'unique_together': {('group', 'name')},
            },
        ),
    ]
