# Generated by Django 5.2.1 on 2025-07-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name_en',
            field=models.CharField(default='', max_length=100, verbose_name='그룹영어명'),
        ),
        migrations.AddField(
            model_name='member',
            name='name_en',
            field=models.CharField(default='', max_length=100, verbose_name='멤버 영어이름'),
        ),
    ]
