# Generated by Django 5.2.1 on 2025-07-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_logo',
            field=models.ImageField(blank=True, null=True, upload_to='group_logo/', verbose_name='그룹 로고 이미지'),
        ),
    ]
