# Generated by Django 5.2.1 on 2025-07-04 03:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sharing_images/', verbose_name='첨부 이미지')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시각')),
            ],
        ),
        migrations.CreateModel(
            name='SharingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('category', models.CharField(choices=[('앨범', '앨범'), ('굿즈', '굿즈'), ('기타', '기타')], max_length=20, verbose_name='카테고리')),
                ('type', models.CharField(choices=[('온라인', '온라인'), ('오프라인', '오프라인')], max_length=10, verbose_name='나눔 형태')),
                ('share_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='나눔 날짜')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='나눔 장소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
            ],
        ),
        migrations.CreateModel(
            name='SharingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='태그명')),
            ],
        ),
    ]
