# Generated by Django 5.2.1 on 2025-07-01 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='태그명')),
            ],
        ),
        migrations.CreateModel(
            name='SharingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('category', models.CharField(choices=[('굿즈', '굿즈'), ('앨범', '앨범')], max_length=20, verbose_name='카테고리')),
                ('type', models.CharField(choices=[('온라인', '온라인'), ('오프라인', '오프라인')], max_length=10, verbose_name='나눔 형태')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sharing_images/', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('tags', models.ManyToManyField(blank=True, related_name='sharing_posts', to='sharing.sharingtag', verbose_name='태그')),
            ],
        ),
    ]
