# Generated by Django 5.2.1 on 2025-07-04 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sharing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sharingpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='sharingimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sharing.sharingpost'),
        ),
        migrations.AddField(
            model_name='sharingpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sharing_posts', to='sharing.sharingtag', verbose_name='태그'),
        ),
    ]
