# Generated by Django 5.2.1 on 2025-07-01 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharingpost',
            name='image',
        ),
        migrations.AddField(
            model_name='sharingpost',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='나눔 장소'),
        ),
        migrations.AddField(
            model_name='sharingpost',
            name='share_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='나눔 날짜'),
        ),
        migrations.AlterField(
            model_name='sharingpost',
            name='category',
            field=models.CharField(choices=[('앨범', '앨범'), ('굿즈', '굿즈'), ('기타', '기타')], max_length=20, verbose_name='카테고리'),
        ),
        migrations.CreateModel(
            name='SharingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sharing_images/', verbose_name='첨부 이미지')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시각')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sharing.sharingpost')),
            ],
        ),
    ]
