# Generated by Django 5.2.1 on 2025-07-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharingpost',
            name='artist',
            field=models.CharField(default='기타', max_length=50, verbose_name='아티스트'),
        ),
        migrations.AddField(
            model_name='sharingpost',
            name='requirement',
            field=models.TextField(default='없음', verbose_name='필수사항'),
            preserve_default=False,
        ),
    ]
