# Generated by Django 5.2.1 on 2025-06-24 08:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='사용자 ID')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('birth_date', models.DateField(verbose_name='생년월일')),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1, verbose_name='성별')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='주소')),
                ('state', models.IntegerField(choices=[(0, '관리자'), (1, '일반 사용자'), (2, '숨김 사용자'), (3, '차단된 사용자')], default=1, verbose_name='사용자 상태')),
                ('manners_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='매너 온도')),
                ('nickname', models.CharField(max_length=100, unique=True, verbose_name='닉네임')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='프로필 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근 수정일')),
                ('bias_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fans_group', to='idols.group', verbose_name='최애 그룹')),
                ('bias_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fans_member', to='idols.member', verbose_name='최애 멤버')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('FOLLOW', '관심 사용자'), ('BLOCK', '차단한 사용자')], max_length=10, verbose_name='관계 유형')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_relations', to='signupFT.user', verbose_name='관계 시작 사용자')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_relations', to='signupFT.user', verbose_name='관계 대상 사용자')),
            ],
            options={
                'verbose_name': '사용자 관계',
                'verbose_name_plural': '사용자 관계 목록',
                'unique_together': {('from_user', 'to_user', 'relation_type')},
            },
        ),
    ]
