# Generated by Django 5.2.1 on 2025-07-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupFT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.IntegerField(choices=[(0, '관리자'), (1, '일반 사용자'), (2, '신고된 사용자'), (3, '정지된 사용자')], default=1, verbose_name='사용자 상태'),
        ),
    ]
