# Generated by Django 5.2.1 on 2025-06-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupFT', '0002_remove_user_bias_group_remove_user_bias_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_marketing',
            field=models.BooleanField(default=False),
        ),
    ]
