# Generated by Django 5.2.1 on 2025-07-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupFT', '0002_alter_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
