# Generated by Django 5.2.1 on 2025-07-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupFT', '0003_user_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelation',
            name='relation_type',
            field=models.CharField(choices=[('FOLLOW', '관심 사용자'), ('BLOCK', '차단한 사용자'), ('REPORT', '신고한 사용자')], max_length=10, verbose_name='관계 유형'),
        ),
    ]
