# Generated by Django 5.2.1 on 2025-07-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupFT', '0004_alter_userrelation_relation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrelation',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='신고 사유'),
        ),
    ]
