# Generated by Django 5.2.1 on 2025-06-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupFT', '0004_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1, null=True, verbose_name='성별'),
        ),
    ]
