# Generated by Django 5.2.1 on 2025-06-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupFT', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reported_by',
            field=models.TextField(blank=True, default='', verbose_name='신고당한 횟수'),
        ),
    ]
