# Generated by Django 5.2.1 on 2025-07-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupFT', '0006_user_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, default='', verbose_name='자기소개'),
        ),
    ]
