# Generated by Django 5.2.1 on 2025-07-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
        ('signupFT', '0007_user_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bias_group',
            field=models.ManyToManyField(blank=True, related_name='fans_group', to='idols.group', verbose_name='최애 그룹'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bias_member',
            field=models.ManyToManyField(blank=True, related_name='fans_member', to='idols.member', verbose_name='최애 멤버'),
        ),
    ]
