# Generated by Django 5.2.1 on 2025-07-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupFT', '0008_alter_user_bias_group_alter_user_bias_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about_me',
        ),
    ]
