# Generated by Django 5.2.1 on 2025-07-01 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문')),
                ('category', models.CharField(choices=[('콘서트', '콘서트'), ('팬사인회', '팬사인회'), ('팝업스토어', '팝업스토어'), ('전시회', '전시회'), ('굿즈샵', '굿즈샵'), ('기타', '기타')], max_length=20, verbose_name='카테고리')),
                ('artist', models.CharField(max_length=50, verbose_name='아티스트')),
                ('event_date', models.DateTimeField(verbose_name='행사 날짜 및 시간')),
                ('location', models.CharField(max_length=100, verbose_name='위치')),
                ('max_people', models.PositiveIntegerField(verbose_name='최대 모집 인원')),
                ('status', models.CharField(choices=[('모집중', '모집중'), ('모집완료', '모집완료')], default='모집중', max_length=10, verbose_name='모집 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='댓글 수')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_companions', to=settings.AUTH_USER_MODEL, verbose_name='참여자 목록')),
            ],
        ),
        migrations.CreateModel(
            name='CompanionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='companion.companionpost', verbose_name='게시글')),
            ],
        ),
    ]
