# Generated by Django 5.2.1 on 2025-07-04 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companionpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='companionpost',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_companions', to=settings.AUTH_USER_MODEL, verbose_name='참여자 목록'),
        ),
        migrations.AddField(
            model_name='companionimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='companion.companionpost'),
        ),
        migrations.AddField(
            model_name='companioncomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='companion.companionpost', verbose_name='게시글'),
        ),
    ]
