# Generated by Django 5.2.1 on 2025-07-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0002_companiontag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companionpost',
            name='status',
            field=models.CharField(choices=[('모집중', '모집중'), ('모집완료', '모집완료'), ('진행중', '진행중')], default='모집중', max_length=10, verbose_name='모집 상태'),
        ),
    ]
