# Generated by Django 5.2.1 on 2025-07-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0003_alter_companionpost_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companioncomment',
            name='author',
        ),
    ]
