# Generated by Django 5.2.1 on 2025-07-02 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0004_remove_companioncomment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='companion_images/', verbose_name='첨부 이미지')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='이미지 설명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='companion.companionpost')),
            ],
        ),
    ]
