# Generated by Django 5.2.1 on 2025-06-24 03:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempIdol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groub', models.CharField(max_length=50)),
                ('member', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Photocard',
            fields=[
                ('pno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='title', max_length=100)),
                ('image', models.ImageField(upload_to='photocards/')),
                ('category', models.CharField(choices=[('앨범', '앨범'), ('특전', '특전'), ('MD', 'MD'), ('공방', '공방'), ('기타', '기타')], default='Album', max_length=20)),
                ('album', models.CharField(default='1집', max_length=50)),
                ('poca_state', models.CharField(choices=[('상', '상'), ('중', '중'), ('하', '하')], default='상', max_length=20)),
                ('tag', models.CharField(max_length=20, null=True)),
                ('trade_type', models.CharField(choices=[('교환', '교환'), ('구매', '구매')], max_length=20, null=True)),
                ('place', models.CharField(choices=[('올림픽공원', '올림픽공원'), ('상암', '상암'), ('더현대', '더현대'), ('고척', '고척'), ('인스파이어', '인스파이어'), ('홍대', '홍대')], max_length=20, null=True)),
                ('sell_state', models.CharField(choices=[('전', '거래전'), ('중', '거래중'), ('후', '거래완료')], default='전', max_length=20)),
                ('buy_state', models.CharField(choices=[('전', '거래전'), ('중', '거래중'), ('후', '거래완료')], max_length=20, null=True)),
                ('hit', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_at', models.DateField(default=datetime.date.today, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('idol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photocards', to='photocard.tempidol')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy', to='photocard.tempuser')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell', to='photocard.tempuser')),
            ],
        ),
    ]
