# Generated by Django 5.2.1 on 2025-07-05 01:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idols', '0001_initial'),
        ('signupFT', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photocard',
            fields=[
                ('pno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='title', max_length=100)),
                ('image', models.ImageField(upload_to='photocards/')),
                ('category', models.CharField(choices=[('앨범', '앨범'), ('특전', '특전'), ('MD', 'MD'), ('공방', '공방'), ('기타', '기타')], default='Album', max_length=20)),
                ('album', models.CharField(default='1집', max_length=50)),
                ('poca_state', models.CharField(choices=[('상', '상'), ('중', '중'), ('하', '하')], default='상', max_length=20)),
                ('tag', models.CharField(blank=True, max_length=20, null=True)),
                ('trade_type', models.CharField(choices=[('판매', '판매'), ('교환', '교환')], max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True)),
                ('place', models.CharField(choices=[('올림픽공원', '올림픽공원'), ('상암', '상암'), ('더현대', '더현대'), ('고척', '고척'), ('인스파이어', '인스파이어'), ('홍대', '홍대')], max_length=20, null=True)),
                ('sell_state', models.CharField(choices=[('전', '거래전'), ('중', '거래중'), ('후', '거래완료')], default='전', max_length=20)),
                ('buy_state', models.CharField(blank=True, choices=[('전', '거래전'), ('중', '거래중'), ('후', '거래완료')], max_length=20, null=True)),
                ('hit', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_at', models.DateField(default=datetime.date.today, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buying_photocards', to='signupFT.user')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photocards', to='idols.member')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_photocards', to='signupFT.user')),
            ],
        ),
        migrations.CreateModel(
            name='TempWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photocard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wished_by_users', to='photocard.photocard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wished_photocards', to='signupFT.user')),
            ],
            options={
                'unique_together': {('user', 'photocard')},
            },
        ),
    ]
