# Generated by Django 5.2.1 on 2025-07-04 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idols', '0001_initial'),
        ('photocard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photocard',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buying_photocards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photocard',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photocards', to='idols.member'),
        ),
        migrations.AddField(
            model_name='photocard',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_photocards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tempwish',
            name='photocard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wished_by_users', to='photocard.photocard'),
        ),
        migrations.AddField(
            model_name='tempwish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wished_photocards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tempwish',
            unique_together={('user', 'photocard')},
        ),
    ]
