# Generated by Django 5.2.1 on 2025-06-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photocard', '0002_alter_photocard_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocard',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
