# Generated by Django 5.2.1 on 2025-07-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photocard', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocard',
            name='trade_type',
            field=models.CharField(choices=[('판매', '판매'), ('교환', '교환')], max_length=20, null=True),
        ),
    ]
