# Generated by Django 5.2.1 on 2025-06-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photocard', '0003_alter_photocard_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocard',
            name='buy_state',
            field=models.CharField(blank=True, choices=[('전', '거래전'), ('중', '거래중'), ('후', '거래완료')], max_length=20, null=True),
        ),
    ]
