# Generated by Django 5.2.1 on 2025-06-24 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photocard', '0004_alter_photocard_buy_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photocard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish', to='photocard.photocard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish', to='photocard.tempuser')),
            ],
        ),
    ]
