# Generated by Django 5.2.1 on 2025-06-24 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photocard', '0005_tempwish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocard',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buying_photocards', to='photocard.tempuser'),
        ),
        migrations.AlterField(
            model_name='photocard',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_photocards', to='photocard.tempuser'),
        ),
        migrations.AlterField(
            model_name='tempwish',
            name='photocard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wished_by_users', to='photocard.photocard'),
        ),
        migrations.AlterField(
            model_name='tempwish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wished_photocards', to='photocard.tempuser'),
        ),
    ]
