# Generated by Django 5.2.1 on 2025-06-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photocard', '0006_alter_photocard_buyer_alter_photocard_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempidol',
            old_name='groub',
            new_name='group',
        ),
    ]
