# Generated by Django 5.2.1 on 2025-06-25 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
        ('photocard', '0007_rename_groub_tempidol_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photocard',
            name='idol',
        ),
        migrations.AddField(
            model_name='photocard',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photocards', to='idols.member'),
        ),
    ]
