# Generated by Django 5.2.1 on 2025-06-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photocard', '0008_remove_photocard_idol_photocard_member'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tempwish',
            unique_together={('user', 'photocard')},
        ),
    ]
