# Generated by Django 5.2.1 on 2025-06-27 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photocard', '0009_alter_tempwish_unique_together'),
        ('signupFT', '0003_user_agree_marketing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocard',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buying_photocards', to='signupFT.user'),
        ),
        migrations.AlterField(
            model_name='photocard',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_photocards', to='signupFT.user'),
        ),
        migrations.AlterField(
            model_name='tempwish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wished_photocards', to='signupFT.user'),
        ),
    ]
