# Generated by Django 5.2.1 on 2025-06-27 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photocard', '0010_alter_photocard_buyer_alter_photocard_seller_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempIdol',
        ),
        migrations.DeleteModel(
            name='TempUser',
        ),
    ]
