# Generated by Django 5.2.1 on 2025-06-13 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('comment', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
