# Generated by Django 5.2.1 on 2025-06-13 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('comment', '0002_rename_comment_comments'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
