# Generated by Django 5.2.1 on 2025-05-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_age_student_ageage_student_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ageage',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(max_length=10),
        ),
    ]
