# Generated by Django 5.2.1 on 2025-05-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_ageage_student_age_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(null=True),
        ),
    ]
