# Generated by Django 5.2.1 on 2025-05-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_gender_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=30),
        ),
    ]
