# Generated by Django 5.2.1 on 2025-07-04 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chgReview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangereview',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='교환 상대방'),
        ),
        migrations.AddField(
            model_name='exchangereview',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chgReview.exchangereview'),
        ),
        migrations.AddField(
            model_name='exchangereview',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='chgReview.reviewtag', verbose_name='태그'),
        ),
    ]
