# Generated by Django 5.2.1 on 2025-07-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chgReview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='태그명')),
            ],
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='overall_score',
            field=models.PositiveSmallIntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], verbose_name='총 평점 (1~5)'),
        ),
        migrations.AddField(
            model_name='exchangereview',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='chgReview.reviewtag', verbose_name='태그'),
        ),
    ]
