# Generated by Django 5.2.1 on 2025-07-01 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chgReview', '0002_reviewtag_alter_exchangereview_overall_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='업로드 시간'),
            preserve_default=False,
        ),
    ]
