# Generated by Django 5.2.1 on 2025-07-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chgReview', '0003_reviewimage_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangereview',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='exchangereview',
            name='category',
        ),
    ]
