# Generated by Django 5.2.1 on 2025-07-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chgReview', '0004_remove_exchangereview_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangereview',
            name='artist',
            field=models.CharField(default='무명', max_length=50, verbose_name='아티스트'),
            preserve_default=False,
        ),
    ]
