# Generated by Django 5.2.1 on 2025-07-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chgReview', '0005_exchangereview_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangereview',
            name='artist',
            field=models.CharField(default='기타', max_length=50, verbose_name='아티스트'),
        ),
    ]
