# Generated by Django 5.2.1 on 2025-07-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chgReview', '0006_alter_exchangereview_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangereview',
            name='transaction_type',
            field=models.CharField(choices=[('교환', '교환'), ('양도', '양도')], default='교환', max_length=10, verbose_name='거래 방식'),
        ),
    ]
