# Generated by Django 5.2.1 on 2025-07-01 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecoratedPhotocard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='포카 이름')),
                ('base_image', models.ImageField(upload_to='decorated/base/', verbose_name='원본 포카')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='decorated/result/', verbose_name='꾸민 이미지 결과')),
                ('brightness', models.IntegerField(default=100, verbose_name='밝기')),
                ('contrast', models.IntegerField(default=100, verbose_name='대비')),
                ('saturation', models.IntegerField(default=100, verbose_name='채도')),
                ('frame_style', models.CharField(blank=True, choices=[('heart', '하트'), ('star', '별'), ('circle', '원형'), ('vintage', '빈티지'), ('polaroid', '폴라로이드'), ('ornate', '화려한')], max_length=20, null=True, verbose_name='프레임 스타일')),
                ('border_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='테두리 색상')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorated_photocards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StickerPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10, verbose_name='스티커 이모지')),
                ('x', models.FloatField(verbose_name='X 좌표 (%)')),
                ('y', models.FloatField(verbose_name='Y 좌표 (%)')),
                ('scale', models.FloatField(default=1.0, verbose_name='크기 배율')),
                ('rotation', models.FloatField(default=0.0, verbose_name='회전 각도')),
                ('photocard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='pocadeco.decoratedphotocard')),
            ],
        ),
    ]
