# Generated by Django 5.2.1 on 2025-07-04 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pocadeco', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decoratedphotocard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorated_photocards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stickerplacement',
            name='photocard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='pocadeco.decoratedphotocard'),
        ),
    ]
