# Generated by Django 5.2.1 on 2025-07-09 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
        ('pocadeco', '0001_initial'),
        ('signupFT', '0003_user_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoratedphotocard',
            name='hit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='decoratedphotocard',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decorated_photocards', to='idols.member'),
        ),
        migrations.AddField(
            model_name='decoratedphotocard',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DecoWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DecoratedPhotocard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wished_by_users', to='pocadeco.decoratedphotocard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deco_wished_photocards', to='signupFT.user')),
            ],
            options={
                'unique_together': {('user', 'DecoratedPhotocard')},
            },
        ),
    ]
