# Generated by Django 5.2.1 on 2025-06-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_remove_comment_cpw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ccate',
            new_name='cdate',
        ),
        migrations.AddField(
            model_name='comment',
            name='cpw',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
