# Generated by Django 5.2.1 on 2025-06-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('P_Code', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('P_MD', models.CharField(max_length=10000)),
                ('Top_MD', models.CharField(max_length=50)),
                ('Low_MD', models.CharField(max_length=50)),
                ('Origin', models.CharField(max_length=50)),
                ('Weight', models.IntegerField(default=0)),
                ('Customer_price', models.IntegerField(default=0)),
                ('Discount_price', models.IntegerField(default=0)),
                ('Stack', models.IntegerField(default=0)),
                ('Main_img', models.ImageField(default=True, upload_to='')),
                ('Sub_img', models.ImageField(default=True, upload_to='')),
                ('Edate', models.DateTimeField(auto_now=True)),
                ('Rdate', models.DateTimeField(auto_now=True)),
                ('Front_top', models.IntegerField(default=0)),
            ],
        ),
    ]
